version: "2"

formatters:
  enable:
    - goimports

linters:
  enable:
    - bodyclose
    - asciicheck
    - dupl
    - rowserrcheck
    - sqlclosecheck
    - unconvert
    - durationcheck
    - errorlint
    - goconst
    - revive
    - gosec
    - misspell
    - nilerr
    - nolintlint
    - prealloc
    - staticcheck
    - thelper
    - wastedassign

  exclusions:
    paths:
      - main
    # Suppress comment-related warnings (to be added gradually).
    presets:
      - comments
    # Excluding configuration per-path, per-linter, per-text and per-source
    rules:
      # Exclude some linters from running on tests files.
      - path: _test\.go
        linters:
          - gocyclo
          - errcheck
          - dupl
          - gosec

  settings:
    revive:
      rules:
        - name: redefines-builtin-id
        - name: var-naming
        - name: unused-parameter
        - name: receiver-naming
        - name: indent-error-flow
        - name: increment-decrement
