// Code generated by "stringer -type=BACnetServicesSupported"; DO NOT EDIT.

package bacnet

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ServicesSupportedAcknowledgeAlaram-0]
	_ = x[ServicesSupportedConfirmedCovNotification-1]
	_ = x[ServicesSupportedConfirmedCovNotificationMultiple-42]
	_ = x[ServicesSupportedConfirmedEventNotification-2]
	_ = x[ServicesSupportedGetAlarmSummary-3]
	_ = x[ServicesSupportedGetEnrollmentSummary-4]
	_ = x[ServicesSupportedGetEventInformation-39]
	_ = x[ServicesSupportedLifeSafetyOperation-37]
	_ = x[ServicesSupportedSubscribeCov-5]
	_ = x[ServicesSupportedSubscribeCovProperty-38]
	_ = x[ServicesSupportedSubscribeCovPropertyMultiple-41]
	_ = x[ServicesSupportedConfirmedAuditNotification-44]
	_ = x[ServicesSupportedAtomicReadFile-6]
	_ = x[ServicesSupportedAtomicWriteFile-7]
	_ = x[ServicesSupportedAddListElement-8]
	_ = x[ServicesSupportedRemoveListElement-9]
	_ = x[ServicesSupportedCreateObject-10]
	_ = x[ServicesSupportedDeleteObject-11]
	_ = x[ServicesSupportedReadProperty-12]
	_ = x[ServicesSupportedReadPropertyMultiple-14]
	_ = x[ServicesSupportedReadRange-35]
	_ = x[ServicesSupportedWriteGroup-40]
	_ = x[ServicesSupportedWriteProperty-15]
	_ = x[ServicesSupportedWritePropertyMultiple-16]
	_ = x[ServicesSupportedAuditLogQuery-45]
	_ = x[ServicesSupportedDeviceCommunicationControl-17]
	_ = x[ServicesSupportedConfirmedPrivateTransfer-18]
	_ = x[ServicesSupportedConfirmedTextMessage-19]
	_ = x[ServicesSupportedReinitializeDevice-20]
	_ = x[ServicesSupportedWhoAmI-47]
	_ = x[ServicesSupportedYouAre-48]
	_ = x[ServicesSupportedAuthRequest-49]
	_ = x[ServicesSupportedVtOpen-21]
	_ = x[ServicesSupportedVtClose-22]
	_ = x[ServicesSupportedVtData-23]
	_ = x[ServicesSupportedIAm-26]
	_ = x[ServicesSupportedIHave-27]
	_ = x[ServicesSupportedUnconfirmedCovNotification-28]
	_ = x[ServicesSupportedUnconfirmedCovNotificationMultiple-43]
	_ = x[ServicesSupportedUnconfirmedEventNotification-29]
	_ = x[ServicesSupportedUnconfirmedPrivateTransfer-30]
	_ = x[ServicesSupportedUnconfirmedTextMessage-31]
	_ = x[ServicesSupportedTimeSynchronization-32]
	_ = x[ServicesSupportedUtcTimeSynchronization-36]
	_ = x[ServicesSupportedWhoHas-33]
	_ = x[ServicesSupportedWhoIs-34]
	_ = x[ServicesSupportedUnconfirmedAuditNotification-46]
	_ = x[ServicesSupportedReadPropertyConditional-13]
	_ = x[ServicesSupportedAuthenticate-24]
	_ = x[ServicesSupportedRequestKey-25]
}

const _BACnetServicesSupported_name = "ServicesSupportedAcknowledgeAlaramServicesSupportedConfirmedCovNotificationServicesSupportedConfirmedEventNotificationServicesSupportedGetAlarmSummaryServicesSupportedGetEnrollmentSummaryServicesSupportedSubscribeCovServicesSupportedAtomicReadFileServicesSupportedAtomicWriteFileServicesSupportedAddListElementServicesSupportedRemoveListElementServicesSupportedCreateObjectServicesSupportedDeleteObjectServicesSupportedReadPropertyServicesSupportedReadPropertyConditionalServicesSupportedReadPropertyMultipleServicesSupportedWritePropertyServicesSupportedWritePropertyMultipleServicesSupportedDeviceCommunicationControlServicesSupportedConfirmedPrivateTransferServicesSupportedConfirmedTextMessageServicesSupportedReinitializeDeviceServicesSupportedVtOpenServicesSupportedVtCloseServicesSupportedVtDataServicesSupportedAuthenticateServicesSupportedRequestKeyServicesSupportedIAmServicesSupportedIHaveServicesSupportedUnconfirmedCovNotificationServicesSupportedUnconfirmedEventNotificationServicesSupportedUnconfirmedPrivateTransferServicesSupportedUnconfirmedTextMessageServicesSupportedTimeSynchronizationServicesSupportedWhoHasServicesSupportedWhoIsServicesSupportedReadRangeServicesSupportedUtcTimeSynchronizationServicesSupportedLifeSafetyOperationServicesSupportedSubscribeCovPropertyServicesSupportedGetEventInformationServicesSupportedWriteGroupServicesSupportedSubscribeCovPropertyMultipleServicesSupportedConfirmedCovNotificationMultipleServicesSupportedUnconfirmedCovNotificationMultipleServicesSupportedConfirmedAuditNotificationServicesSupportedAuditLogQueryServicesSupportedUnconfirmedAuditNotificationServicesSupportedWhoAmIServicesSupportedYouAreServicesSupportedAuthRequest"

var _BACnetServicesSupported_index = [...]uint16{0, 34, 75, 118, 150, 187, 216, 247, 279, 310, 344, 373, 402, 431, 471, 508, 538, 576, 619, 660, 697, 732, 755, 779, 802, 831, 858, 878, 900, 943, 988, 1031, 1070, 1106, 1129, 1151, 1177, 1216, 1252, 1289, 1325, 1352, 1397, 1446, 1497, 1540, 1570, 1615, 1638, 1661, 1689}

func (i BACnetServicesSupported) String() string {
	if i >= BACnetServicesSupported(len(_BACnetServicesSupported_index)-1) {
		return "BACnetServicesSupported(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _BACnetServicesSupported_name[_BACnetServicesSupported_index[i]:_BACnetServicesSupported_index[i+1]]
}
