// Code generated by "stringer -type=BACnetConfirmedServiceChoice"; DO NOT EDIT.

package bacnet

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ConfirmedServiceChoiceAcknowledgeAlaram-0]
	_ = x[ConfirmedServiceChoiceConfimedAuditNotification-32]
	_ = x[ConfirmedServiceChoiceConfirmedCovNotification-1]
	_ = x[ConfirmedServiceChoiceConfirmedCovNotificaitonMultiple-31]
	_ = x[ConfirmedServiceChoiceConfirmedEventNotification-2]
	_ = x[ConfirmedServiceChoiceGetAlramSummary-3]
	_ = x[ConfirmedServiceChoiceGetEnrollmentSummary-4]
	_ = x[ConfirmedServiceChoiceGetEventInformation-29]
	_ = x[ConfirmedServiceChoiceLifeSafetyOperation-27]
	_ = x[ConfirmedServiceChoiceSubscribeCov-5]
	_ = x[ConfirmedServiceChoiceSubscribeCovProperty-28]
	_ = x[ConfirmedServiceChoiceSubscribeCovPropertyMultiple-30]
	_ = x[ConfirmedServiceChoiceAtomicReadFile-6]
	_ = x[ConfirmedServiceChoiceAtomicWriteFile-7]
	_ = x[ConfirmedServiceChoiceAddListElement-8]
	_ = x[ConfirmedServiceChoiceRemoveListElement-9]
	_ = x[ConfirmedServiceChoiceCreateObject-10]
	_ = x[ConfirmedServiceChoiceDeleteObject-11]
	_ = x[ConfirmedServiceChoiceReadProperty-12]
	_ = x[ConfirmedServiceChoiceReadPropertyMultiple-14]
	_ = x[ConfirmedServiceChoiceReadRange-26]
	_ = x[ConfirmedServiceChoiceWriteProperty-15]
	_ = x[ConfirmedServiceChoiceWritePropertyMultiple-16]
	_ = x[ConfirmedServiceChoiceAuditLogQuery-33]
	_ = x[ConfirmedServiceChoiceDeviceCommunicationControl-17]
	_ = x[ConfirmedServiceChoiceConfirmedPrivateTransfer-18]
	_ = x[ConfirmedServiceChoiceConfirmedTextMessage-19]
	_ = x[ConfirmedServiceChoiceReinitializeDevice-20]
	_ = x[ConfirmedServiceChoiceAuthRequest-34]
	_ = x[ConfirmedServiceChoiceVtOpen-21]
	_ = x[ConfirmedServiceChoiceVtClose-22]
	_ = x[ConfirmedServiceChoiceVtData-23]
}

const (
	_BACnetConfirmedServiceChoice_name_0 = "ConfirmedServiceChoiceAcknowledgeAlaramConfirmedServiceChoiceConfirmedCovNotificationConfirmedServiceChoiceConfirmedEventNotificationConfirmedServiceChoiceGetAlramSummaryConfirmedServiceChoiceGetEnrollmentSummaryConfirmedServiceChoiceSubscribeCovConfirmedServiceChoiceAtomicReadFileConfirmedServiceChoiceAtomicWriteFileConfirmedServiceChoiceAddListElementConfirmedServiceChoiceRemoveListElementConfirmedServiceChoiceCreateObjectConfirmedServiceChoiceDeleteObjectConfirmedServiceChoiceReadProperty"
	_BACnetConfirmedServiceChoice_name_1 = "ConfirmedServiceChoiceReadPropertyMultipleConfirmedServiceChoiceWritePropertyConfirmedServiceChoiceWritePropertyMultipleConfirmedServiceChoiceDeviceCommunicationControlConfirmedServiceChoiceConfirmedPrivateTransferConfirmedServiceChoiceConfirmedTextMessageConfirmedServiceChoiceReinitializeDeviceConfirmedServiceChoiceVtOpenConfirmedServiceChoiceVtCloseConfirmedServiceChoiceVtData"
	_BACnetConfirmedServiceChoice_name_2 = "ConfirmedServiceChoiceReadRangeConfirmedServiceChoiceLifeSafetyOperationConfirmedServiceChoiceSubscribeCovPropertyConfirmedServiceChoiceGetEventInformationConfirmedServiceChoiceSubscribeCovPropertyMultipleConfirmedServiceChoiceConfirmedCovNotificaitonMultipleConfirmedServiceChoiceConfimedAuditNotificationConfirmedServiceChoiceAuditLogQueryConfirmedServiceChoiceAuthRequest"
)

var (
	_BACnetConfirmedServiceChoice_index_0 = [...]uint16{0, 39, 85, 133, 170, 212, 246, 282, 319, 355, 394, 428, 462, 496}
	_BACnetConfirmedServiceChoice_index_1 = [...]uint16{0, 42, 77, 120, 168, 214, 256, 296, 324, 353, 381}
	_BACnetConfirmedServiceChoice_index_2 = [...]uint16{0, 31, 72, 114, 155, 205, 259, 306, 341, 374}
)

func (i BACnetConfirmedServiceChoice) String() string {
	switch {
	case i <= 12:
		return _BACnetConfirmedServiceChoice_name_0[_BACnetConfirmedServiceChoice_index_0[i]:_BACnetConfirmedServiceChoice_index_0[i+1]]
	case 14 <= i && i <= 23:
		i -= 14
		return _BACnetConfirmedServiceChoice_name_1[_BACnetConfirmedServiceChoice_index_1[i]:_BACnetConfirmedServiceChoice_index_1[i+1]]
	case 26 <= i && i <= 34:
		i -= 26
		return _BACnetConfirmedServiceChoice_name_2[_BACnetConfirmedServiceChoice_index_2[i]:_BACnetConfirmedServiceChoice_index_2[i+1]]
	default:
		return "BACnetConfirmedServiceChoice(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
