// Code generated by "stringer -type=BACnetObjectTypesSupported"; DO NOT EDIT.

package bacnet

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ObjectTypesSupportedAnalogInput-0]
	_ = x[ObjectTypesSupportedAnalogOutput-1]
	_ = x[ObjectTypesSupportedAnalogValue-2]
	_ = x[ObjectTypesSupportedBinaryInput-3]
	_ = x[ObjectTypesSupportedBinaryOutput-4]
	_ = x[ObjectTypesSupportedBinaryValue-5]
	_ = x[ObjectTypesSupportedCalendar-6]
	_ = x[ObjectTypesSupportedCommand-7]
	_ = x[ObjectTypesSupportedDevice-8]
	_ = x[ObjectTypesSupportedEventEnrollment-9]
	_ = x[ObjectTypesSupportedFile-10]
	_ = x[ObjectTypesSupportedGroup-11]
	_ = x[ObjectTypesSupportedLoop-12]
	_ = x[ObjectTypesSupportedMultiStateInput-13]
	_ = x[ObjectTypesSupportedMultiStateOutput-14]
	_ = x[ObjectTypesSupportedNotificationClass-15]
	_ = x[ObjectTypesSupportedProgram-16]
	_ = x[ObjectTypesSupportedSchedule-17]
	_ = x[ObjectTypesSupportedAveraging-18]
	_ = x[ObjectTypesSupportedMultiStateValue-19]
	_ = x[ObjectTypesSupportedTrendLog-20]
	_ = x[ObjectTypesSupportedLifeSafetyPoint-21]
	_ = x[ObjectTypesSupportedLifeSafetyZone-22]
	_ = x[ObjectTypesSupportedAccumulator-23]
	_ = x[ObjectTypesSupportedPulseConverter-24]
	_ = x[ObjectTypesSupportedEventLog-25]
	_ = x[ObjectTypesSupportedGlobalGroup-26]
	_ = x[ObjectTypesSupportedTrendLogMultiple-27]
	_ = x[ObjectTypesSupportedLoadControl-28]
	_ = x[ObjectTypesSupportedStructuredView-29]
	_ = x[ObjectTypesSupportedAccessDoor-30]
	_ = x[ObjectTypesSupportedTimer-31]
	_ = x[ObjectTypesSupportedAccessCredential-33]
	_ = x[ObjectTypesSupportedAccessPoint-34]
	_ = x[ObjectTypesSupportedAccessRights-34]
	_ = x[ObjectTypesSupportedAccessUser-35]
	_ = x[ObjectTypesSupportedAccessZone-36]
	_ = x[ObjectTypesSupportedCredentialInput-37]
	_ = x[ObjectTypesSupportedBitstringValue-39]
	_ = x[ObjectTypesSupportedCharacterstringValue-40]
	_ = x[ObjectTypesSupportedDatePatternValue-41]
	_ = x[ObjectTypesSupportedDateValue-42]
	_ = x[ObjectTypesSupportedDatetimePatternValue-43]
	_ = x[ObjectTypesSupportedDatetimeValue-44]
	_ = x[ObjectTypesSupportedIntegerValue-45]
	_ = x[ObjectTypesSupportedLargeAnalogValue-46]
	_ = x[ObjectTypesSupportedOctetStringValue-47]
	_ = x[ObjectTypesSupportedPositiveIntegerValue-48]
	_ = x[ObjectTypesSupportedTimePatternValue-49]
	_ = x[ObjectTypesSupportedTimeValue-50]
	_ = x[ObjectTypesSupportedNotificationForwarder-51]
	_ = x[ObjectTypesSupportedAlertEnrollment-52]
	_ = x[ObjectTypesSupportedChannel-53]
	_ = x[ObjectTypesSupportedLightingOutput-54]
	_ = x[ObjectTypesSupportedBinaryLightingOutput-55]
	_ = x[ObjectTypesSupportedNetworkPort-56]
	_ = x[ObjectTypesSupportedElevatorGroup-57]
	_ = x[ObjectTypesSupportedEscalator-58]
	_ = x[ObjectTypesSupportedLift-59]
	_ = x[ObjectTypesSupportedStaging-60]
	_ = x[ObjectTypesSupportedAuditLog-61]
	_ = x[ObjectTypesSupportedAuditReporter-62]
	_ = x[ObjectTypesSupportedColor-63]
	_ = x[ObjectTypesSupportedColorTemperature-64]
}

const (
	_BACnetObjectTypesSupported_name_0 = "ObjectTypesSupportedAnalogInputObjectTypesSupportedAnalogOutputObjectTypesSupportedAnalogValueObjectTypesSupportedBinaryInputObjectTypesSupportedBinaryOutputObjectTypesSupportedBinaryValueObjectTypesSupportedCalendarObjectTypesSupportedCommandObjectTypesSupportedDeviceObjectTypesSupportedEventEnrollmentObjectTypesSupportedFileObjectTypesSupportedGroupObjectTypesSupportedLoopObjectTypesSupportedMultiStateInputObjectTypesSupportedMultiStateOutputObjectTypesSupportedNotificationClassObjectTypesSupportedProgramObjectTypesSupportedScheduleObjectTypesSupportedAveragingObjectTypesSupportedMultiStateValueObjectTypesSupportedTrendLogObjectTypesSupportedLifeSafetyPointObjectTypesSupportedLifeSafetyZoneObjectTypesSupportedAccumulatorObjectTypesSupportedPulseConverterObjectTypesSupportedEventLogObjectTypesSupportedGlobalGroupObjectTypesSupportedTrendLogMultipleObjectTypesSupportedLoadControlObjectTypesSupportedStructuredViewObjectTypesSupportedAccessDoorObjectTypesSupportedTimer"
	_BACnetObjectTypesSupported_name_1 = "ObjectTypesSupportedAccessCredentialObjectTypesSupportedAccessPointObjectTypesSupportedAccessUserObjectTypesSupportedAccessZoneObjectTypesSupportedCredentialInput"
	_BACnetObjectTypesSupported_name_2 = "ObjectTypesSupportedBitstringValueObjectTypesSupportedCharacterstringValueObjectTypesSupportedDatePatternValueObjectTypesSupportedDateValueObjectTypesSupportedDatetimePatternValueObjectTypesSupportedDatetimeValueObjectTypesSupportedIntegerValueObjectTypesSupportedLargeAnalogValueObjectTypesSupportedOctetStringValueObjectTypesSupportedPositiveIntegerValueObjectTypesSupportedTimePatternValueObjectTypesSupportedTimeValueObjectTypesSupportedNotificationForwarderObjectTypesSupportedAlertEnrollmentObjectTypesSupportedChannelObjectTypesSupportedLightingOutputObjectTypesSupportedBinaryLightingOutputObjectTypesSupportedNetworkPortObjectTypesSupportedElevatorGroupObjectTypesSupportedEscalatorObjectTypesSupportedLiftObjectTypesSupportedStagingObjectTypesSupportedAuditLogObjectTypesSupportedAuditReporterObjectTypesSupportedColorObjectTypesSupportedColorTemperature"
)

var (
	_BACnetObjectTypesSupported_index_0 = [...]uint16{0, 31, 63, 94, 125, 157, 188, 216, 243, 269, 304, 328, 353, 377, 412, 448, 485, 512, 540, 569, 604, 632, 667, 701, 732, 766, 794, 825, 861, 892, 926, 956, 981}
	_BACnetObjectTypesSupported_index_1 = [...]uint8{0, 36, 67, 97, 127, 162}
	_BACnetObjectTypesSupported_index_2 = [...]uint16{0, 34, 74, 110, 139, 179, 212, 244, 280, 316, 356, 392, 421, 462, 497, 524, 558, 598, 629, 662, 691, 715, 742, 770, 803, 828, 864}
)

func (i BACnetObjectTypesSupported) String() string {
	switch {
	case i <= 31:
		return _BACnetObjectTypesSupported_name_0[_BACnetObjectTypesSupported_index_0[i]:_BACnetObjectTypesSupported_index_0[i+1]]
	case 33 <= i && i <= 37:
		i -= 33
		return _BACnetObjectTypesSupported_name_1[_BACnetObjectTypesSupported_index_1[i]:_BACnetObjectTypesSupported_index_1[i+1]]
	case 39 <= i && i <= 64:
		i -= 39
		return _BACnetObjectTypesSupported_name_2[_BACnetObjectTypesSupported_index_2[i]:_BACnetObjectTypesSupported_index_2[i+1]]
	default:
		return "BACnetObjectTypesSupported(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
