// Code generated by "stringer -type=BACnetDeviceStatus"; DO NOT EDIT.

package bacnet

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[DeviceStatusOperational-0]
	_ = x[DeviceStatusOperationalReadOnly-1]
	_ = x[DeviceStatusDownloadRequired-2]
	_ = x[DeviceStatusDownloadInProgress-3]
	_ = x[DeviceStatusNonOperational-4]
	_ = x[DeviceStatusBackupInProgress-5]
}

const _BACnetDeviceStatus_name = "DeviceStatusOperationalDeviceStatusOperationalReadOnlyDeviceStatusDownloadRequiredDeviceStatusDownloadInProgressDeviceStatusNonOperationalDeviceStatusBackupInProgress"

var _BACnetDeviceStatus_index = [...]uint8{0, 23, 54, 82, 112, 138, 166}

func (i BACnetDeviceStatus) String() string {
	if i >= BACnetDeviceStatus(len(_BACnetDeviceStatus_index)-1) {
		return "BACnetDeviceStatus(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _BACnetDeviceStatus_name[_BACnetDeviceStatus_index[i]:_BACnetDeviceStatus_index[i+1]]
}
