// Code generated by "stringer -type=BACnetUnconfirmedServiceChoice"; DO NOT EDIT.

package bacnet

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[UnconfirmedServiceChoiceIAm-0]
	_ = x[UnconfirmedServiceChoiceIHave-1]
	_ = x[UnconfirmedServiceChoiceUnconfirmedCovNotification-2]
	_ = x[UnconfirmedServiceChoiceUnconfirmedEventNotification-3]
	_ = x[UnconfirmedServiceChoiceUnconfirmedPrivateTransfer-4]
	_ = x[UnconfirmedServiceChoiceUnconfirmedTextMessage-5]
	_ = x[UnconfirmedServiceChoiceTimeSynchronization-6]
	_ = x[UnconfirmedServiceChoiceWhoHas-7]
	_ = x[UnconfirmedServiceChoiceWhoIs-8]
	_ = x[UnconfirmedServiceChoiceUtcTimeSynchronization-9]
	_ = x[UnconfirmedServiceChoiceWriteGroup-10]
	_ = x[UnconfirmedServiceChoiceUnconfirmedCovNotificationMultiple-11]
	_ = x[UnconfirmedServiceChoiceUnconfirmedAuditNotification-12]
	_ = x[UnconfirmedServiceChoiceWhoAmI-13]
	_ = x[UnconfirmedServiceChoiceYouAre-14]
}

const _BACnetUnconfirmedServiceChoice_name = "UnconfirmedServiceChoiceIAmUnconfirmedServiceChoiceIHaveUnconfirmedServiceChoiceUnconfirmedCovNotificationUnconfirmedServiceChoiceUnconfirmedEventNotificationUnconfirmedServiceChoiceUnconfirmedPrivateTransferUnconfirmedServiceChoiceUnconfirmedTextMessageUnconfirmedServiceChoiceTimeSynchronizationUnconfirmedServiceChoiceWhoHasUnconfirmedServiceChoiceWhoIsUnconfirmedServiceChoiceUtcTimeSynchronizationUnconfirmedServiceChoiceWriteGroupUnconfirmedServiceChoiceUnconfirmedCovNotificationMultipleUnconfirmedServiceChoiceUnconfirmedAuditNotificationUnconfirmedServiceChoiceWhoAmIUnconfirmedServiceChoiceYouAre"

var _BACnetUnconfirmedServiceChoice_index = [...]uint16{0, 27, 56, 106, 158, 208, 254, 297, 327, 356, 402, 436, 494, 546, 576, 606}

func (i BACnetUnconfirmedServiceChoice) String() string {
	if i >= BACnetUnconfirmedServiceChoice(len(_BACnetUnconfirmedServiceChoice_index)-1) {
		return "BACnetUnconfirmedServiceChoice(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _BACnetUnconfirmedServiceChoice_name[_BACnetUnconfirmedServiceChoice_index[i]:_BACnetUnconfirmedServiceChoice_index[i+1]]
}
