// Code generated by "stringer -type=BVLCType"; DO NOT EDIT.

package bacip

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[TypeBacnetIP-129]
}

const _BVLCType_name = "TypeBacnetIP"

var _BVLCType_index = [...]uint8{0, 12}

func (i BVLCType) String() string {
	i -= 129
	if i >= BVLCType(len(_BVLCType_index)-1) {
		return "BVLCType(" + strconv.FormatInt(int64(i+129), 10) + ")"
	}
	return _BVLCType_name[_BVLCType_index[i]:_BVLCType_index[i+1]]
}
