// Code generated by "stringer -type=NetworkMessageType"; DO NOT EDIT.

package bacip

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[WhoIsRouterToNetwork-0]
	_ = x[IAmRouterToNetwork-1]
	_ = x[ICouldBeRouterToNetwork-2]
	_ = x[RejectMessageToNetwork-3]
	_ = x[RouterBusyToNewtork-4]
	_ = x[RouterAvailableToNetwork-5]
	_ = x[InitializeRoutingTable-6]
	_ = x[InitializeRoutingTableAck-7]
	_ = x[EstablishConnectionToNetwork-8]
	_ = x[DisconnectConnectionToNetwork-9]
	_ = x[ChallengeRequest-10]
	_ = x[SecurityPayload-11]
	_ = x[SecurityResponse-12]
	_ = x[RequestKeyUpdate-13]
	_ = x[UpdateKeySet-14]
	_ = x[UpdateDistributionKey-15]
	_ = x[RequestMasterKey-16]
	_ = x[SetMasterKey-17]
	_ = x[WhatIsNetworkNumber-18]
	_ = x[NetworkNumberIs-19]
}

const _NetworkMessageType_name = "WhoIsRouterToNetworkIAmRouterToNetworkICouldBeRouterToNetworkRejectMessageToNetworkRouterBusyToNewtorkRouterAvailableToNetworkInitializeRoutingTableInitializeRoutingTableAckEstablishConnectionToNetworkDisconnectConnectionToNetworkChallengeRequestSecurityPayloadSecurityResponseRequestKeyUpdateUpdateKeySetUpdateDistributionKeyRequestMasterKeySetMasterKeyWhatIsNetworkNumberNetworkNumberIs"

var _NetworkMessageType_index = [...]uint16{0, 20, 38, 61, 83, 102, 126, 148, 173, 201, 230, 246, 261, 277, 293, 305, 326, 342, 354, 373, 388}

func (i NetworkMessageType) String() string {
	if i >= NetworkMessageType(len(_NetworkMessageType_index)-1) {
		return "NetworkMessageType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _NetworkMessageType_name[_NetworkMessageType_index[i]:_NetworkMessageType_index[i+1]]
}
