// Code generated by "stringer -type=NetworkMessageType"; DO NOT EDIT.

package bacip

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[WhoIsRouterToNetwork-0]
	_ = x[IAmRouterToNetwork-1]
	_ = x[ICouldBeRouterToNetwork-2]
	_ = x[RejectMessageToNetwork-3]
	_ = x[RouterBusyToNewtork-4]
	_ = x[RouterAvailableToNetwork-5]
	_ = x[InitializeRoutingTable-6]
	_ = x[InitializeRoutingTableAck-7]
	_ = x[EstablishConnectionToNetwork-8]
	_ = x[DisconnectConnectionToNetwork-9]
	_ = x[ChallengeRequest-10]
	_ = x[SecurityPayload-11]
	_ = x[SecurityResponse-12]
	_ = x[RequestKeyUpdate-13]
	_ = x[UpdateKeySet-14]
	_ = x[UpdateDistributionKey-15]
	_ = x[RequestMasterKey-16]
	_ = x[SetMasterKey-17]
	_ = x[WhatIsNetworkNumber-18]
	_ = x[NetworkNumberIs-19]
}

const _NetworkMessageType_name = "WHO_IS_ROUTER_TO_NETWORKI_AM_ROUTER_TO_NETWORKI_COULD_BE_ROUTER_TO_NETWORKREJECT_MESSAGE_TO_NETWORKROUTER_BUSY_TO_NETWORKROUTER_AVAILABLE_TO_NETWORKINITIALIZE_ROUTING_TABLEINITIALIZE_ROUTING_TABLE_ACKESTABLISH_CONNECTION_TO_NETWORKDISCONNECT_CONNECTION_TO_NETWORKCHALLENGE_REQUESTSECURITY_PAYLOADSECURITY_RESPONSEREQUEST_KEY_UPDATEUPDATE_KEY_SETUPDATE_DISTRIBUTION_KEYREQUEST_MASTER_KEYSET_MASTER_KEYWHAT_IS_NETWORK_NUMBERNETWORK_NUMBER_IS"

var _NetworkMessageType_index = [...]uint16{0, 24, 46, 74, 99, 121, 148, 172, 200, 231, 263, 280, 296, 313, 331, 345, 368, 386, 400, 422, 439}

func (i NetworkMessageType) String() string {
	if i >= NetworkMessageType(len(_NetworkMessageType_index)-1) {
		return "NetworkMessageType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _NetworkMessageType_name[_NetworkMessageType_index[i]:_NetworkMessageType_index[i+1]]
}
