// Code generated by "stringer -type=PDUType"; DO NOT EDIT.

package bacip

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ConfirmedServiceRequest-0]
	_ = x[UnconfirmedServiceRequest-1]
	_ = x[SimpleAck-2]
	_ = x[ComplexAck-3]
	_ = x[SegmentAck-4]
	_ = x[Error-5]
	_ = x[Reject-6]
	_ = x[Abort-7]
}

const _PDUType_name = "ConfirmedServiceRequestUnconfirmedServiceRequestSimpleAckComplexAckSegmentAckErrorRejectAbort"

var _PDUType_index = [...]uint8{0, 23, 48, 57, 67, 77, 82, 88, 93}

func (i PDUType) String() string {
	if i >= PDUType(len(_PDUType_index)-1) {
		return "PDUType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _PDUType_name[_PDUType_index[i]:_PDUType_index[i+1]]
}
