// Code generated by "stringer -type=BVLCSCFunction"; DO NOT EDIT.

package linklayer

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[BVLCSCFuncResult-0]
	_ = x[BVLCSCFuncEncapsulatedNPDU-1]
	_ = x[BVLCSCFuncAddressResolution-2]
	_ = x[BVLCSCFuncAddressResolutionACK-3]
	_ = x[BVLCSCFuncAdvertisement-4]
	_ = x[BVLCSCFuncAdvertisementSolicitation-5]
	_ = x[BVLCSCFuncConnectRequest-6]
	_ = x[BVLCSCFuncConnectAccept-7]
	_ = x[BVLCSCFuncDisconnectRequest-8]
	_ = x[BVLCSCFuncDisconnectACK-9]
	_ = x[BVLCSCFuncHeartbeatRequest-10]
	_ = x[BVLCSCFuncHeartbeatACK-11]
	_ = x[BVLCSCFuncProprietaryMessage-12]
}

const _BVLCSCFunction_name = "BVLCSCFuncResultBVLCSCFuncEncapsulatedNPDUBVLCSCFuncAddressResolutionBVLCSCFuncAddressResolutionACKBVLCSCFuncAdvertisementBVLCSCFuncAdvertisementSolicitationBVLCSCFuncConnectRequestBVLCSCFuncConnectAcceptBVLCSCFuncDisconnectRequestBVLCSCFuncDisconnectACKBVLCSCFuncHeartbeatRequestBVLCSCFuncHeartbeatACKBVLCSCFuncProprietaryMessage"

var _BVLCSCFunction_index = [...]uint16{0, 16, 42, 69, 99, 122, 157, 181, 204, 231, 254, 280, 302, 330}

func (i BVLCSCFunction) String() string {
	if i >= BVLCSCFunction(len(_BVLCSCFunction_index)-1) {
		return "BVLCSCFunction(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _BVLCSCFunction_name[_BVLCSCFunction_index[i]:_BVLCSCFunction_index[i+1]]
}
