// Code generated by "stringer -type=NetworkMessageType"; DO NOT EDIT.

package networklayer

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[WhoIsRouterToNetwork-0]
	_ = x[IAmRouterToNetwork-1]
	_ = x[ICouldBeRouterToNetwork-2]
	_ = x[RejectMessageToNetwork-3]
	_ = x[RouterBusyToNewtork-4]
	_ = x[RouterAvailableToNetwork-5]
	_ = x[InitializeRoutingTable-6]
	_ = x[InitializeRoutingTableAck-7]
	_ = x[EstablishConnectionToNetwork-8]
	_ = x[DisconnectConnectionToNetwork-9]
	_ = x[ChallengeRequest-10]
	_ = x[WhatIsNetworkNumber-18]
	_ = x[NetworkNumberIs-19]
}

const (
	_NetworkMessageType_name_0 = "WhoIsRouterToNetworkIAmRouterToNetworkICouldBeRouterToNetworkRejectMessageToNetworkRouterBusyToNewtorkRouterAvailableToNetworkInitializeRoutingTableInitializeRoutingTableAckEstablishConnectionToNetworkDisconnectConnectionToNetworkChallengeRequest"
	_NetworkMessageType_name_1 = "WhatIsNetworkNumberNetworkNumberIs"
)

var (
	_NetworkMessageType_index_0 = [...]uint8{0, 20, 38, 61, 83, 102, 126, 148, 173, 201, 230, 246}
	_NetworkMessageType_index_1 = [...]uint8{0, 19, 34}
)

func (i NetworkMessageType) String() string {
	switch {
	case i <= 10:
		return _NetworkMessageType_name_0[_NetworkMessageType_index_0[i]:_NetworkMessageType_index_0[i+1]]
	case 18 <= i && i <= 19:
		i -= 18
		return _NetworkMessageType_name_1[_NetworkMessageType_index_1[i]:_NetworkMessageType_index_1[i+1]]
	default:
		return "NetworkMessageType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
