// Code generated by "stringer -type=NPDUPriority"; DO NOT EDIT.

package networklayer

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[LifeSafety-3]
	_ = x[CriticalEquipment-2]
	_ = x[UrgentPriority-1]
	_ = x[NormalPriority-0]
}

const _NPDUPriority_name = "NormalPriorityUrgentPriorityCriticalEquipmentLifeSafety"

var _NPDUPriority_index = [...]uint8{0, 14, 28, 45, 55}

func (i NPDUPriority) String() string {
	if i >= NPDUPriority(len(_NPDUPriority_index)-1) {
		return "NPDUPriority(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _NPDUPriority_name[_NPDUPriority_index[i]:_NPDUPriority_index[i+1]]
}
